import {Kumbh_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import {CartProvider} from "@/app/contexts/CartProvider";

const ksans = Kumbh_Sans({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={ksans.className}>
        <div className='container mx-auto px-0 lg:px-32'>
            <CartProvider>
                <Navbar/>
                {children}
            </CartProvider>
        </div>
        </body>
        </html>
    );
}
